# 가설 검정

## 왜 가설 검정이 필요할까??
- 모집단 전체를 전수조사 할 수 있다면 가설검정은 필요가 없다.
- 비용, 시간 등의 문제로 모집단의 일부인 "표본(sample)"만 관찰할 수 있을 때, 그 표본을 근거로 모집단에 대한
결론을 통계적으로 추론하기 위해 가설 검정을 사용한다.
- 작업3번 시험에서 주어지는 데이터는 항상 모집단에서 뽑은 표본 데이터라고 가정하고 문제를 푼다.

## 귀무가설 vs 대립가설

### 귀무가설
- 기존에 알려진 사실, 변화, 차이가 "없다"라는 주장
- ex) 아메리카노 한 잔의 원두는 20g이다.

### 대립가설
- 새로 입증하고자 하는 주장, 변화, 차이가 "있다"라는 주장
- ex) 아메리카노 한 잔의 원두는 20g이 아니다.

- 검정 결과를 해석할 때 통계학에서는 귀무가설이 옳다고 밝혀져도 "채택한다"보다는 "기각하지 못한다." 라는
표현을 정확한 용어로 사용한다.
- 시험 답안 작성시에는 "귀무가설 채택" 또는 "귀무가설 기각" 처럼 명확하게 답한다.

- p-value < 유의수준 : 귀무가설 기각, 대립가설 채택
- p-value >= 유의수준 : 귀무가설 채택, 대립가설 기각

### 가설검정 프로세스 4단계 (교재 pdf에 있다.)
1. 통계적 가설 설정 : 귀무가설과 대립가설을 정의
2. 유의수준 결정 : 보통 0.05 또는 0.01 (문제에서 특별히 안내하지 않으면 0.05가 기본)
3. 검정 통계량 및 유의 확률(p-value) 계산 : scipy.stats 각 검정 함수 사용
4. 결과 도출 : p-value와 유의수준을 비교해 기각/채택 결론을 도출

## 1. 단일 표본 검정 (One-sample t-test)
- 이 표본의 평균이 특정 기준값과 통계적으로 다른가?? 를 검정
- ex) 영화관 팝콘 라지 사이즈의 평균 무게가 알려진 120g과 같은지 확인

In [ ]:
import pandas as pd

# 30개의 팝콘 무게 데이터 (weights 컬럼 하나만 있는 데이터프레임)
df = pd.DataFrame({
    'weights':[122, 121, 120, 119, 125, 115, 121, 118, 117, 127,
           123, 129, 119, 124, 114, 126, 122, 124, 121, 116,
           120, 123, 127, 118, 122, 117, 124, 125, 123, 121],
})

In [2]:
df.head()

   weights
0      122
1      121
2      120
3      119
4      125

### ttest_1samp(a, popmean, alternative)
- a : 모집단에서 뽑은 표본 데이터
- popmean : 비교하려는 모집단의 평균(기대값) μ0로 표시
    - μ : 표본이 속한 모집단의 실제 평균
    - μ0 : 귀무가설에서 주장하는 (기존에 알려진) 평균값
- alternative : 대립가설의 방향을 정의
    - 'greater' p > μ0 : 표본 평균이 기준값보다 크다.
    - 'less' p < μ0 : 표본 평균이 기준값보다 작다.
    - 'two-sided' 기본값, 표본 평균이 기준값과 다르다.

In [3]:
from scipy import stats

t_statisitc, p_value = stats.ttest_1samp(df['weights'], 120)

In [4]:
print(f't_statisitc: {t_statisitc}, p-value: {p_value}')

t_statisitc: 2.1155384372682344, p-value: 0.0430929570666092

In [5]:
# 양측 검정 - 기본값
print(stats.ttest_1samp(df['weights'],120, alternative='two-sided'))

TtestResult(statistic=np.float64(2.1155384372682344), pvalue=np.float64(0.0430929570666092), df=np.int64(29))

In [6]:
# 단측 검정 - 오른쪽 --> 평균이 120보다 크다를 대립가설로 검정
print(stats.ttest_1samp(df['weights'],120,alternative='greater'))

TtestResult(statistic=np.float64(2.1155384372682344), pvalue=np.float64(0.0215464785333046), df=np.int64(29))

In [7]:
# 단측 검정 - 왼쪽 --> 평균이 120보다 작다를 대립가설로 검정
print(stats.ttest_1samp(df['weights'],120,alternative='less'))

TtestResult(statistic=np.float64(2.1155384372682344), pvalue=np.float64(0.9784535214666954), df=np.int64(29))

#### 주의할 점
- 같은 데이터라도 어떤 alternative 를 사용하느냐에 따라 p-value가 달라지고, 결론이 뒤바뀔 수있다.
- 문제의 지문의 방향성을 정확히 체크해야 한다.

### 비모수 검정 - 정규성이 깨졌을 때
- 정규성 검정에는 "귀무가설 채택"을 기대한다.
- 일반적인 가설검정(t-검정 등)에서는 연구자가 대립가설의 채택을 기대하는 경우가 많다.
- 데이터가 정규분포를 "따른다"는 귀무가설이 채택되기를 기대하는 것이 일반적이다.
- 그래야 모수적 방법인 t-검정을 그대로 사용할 수 있기 때문이다.

- 귀무가설(μ0) : 데이터가 정규분포를 따른다.
- 대립가설(μ1) : 데이터가 정규분포를 따르지 않는다.

In [8]:
import pandas as pd
# 마지막 값(142)이 다른 값들보다 확연히 큰 이상치성 데이터
df = pd.DataFrame({
    'weights':[125, 126, 118, 124, 117, 127, 123, 122, 119, 142]
})

In [9]:
# 정규성이 깨졌으므로 t-검정 대신 Wilcoxon 부호순위 검정(비모수) 사용
# 각 값에서 기준값 120을 뺀 차이값을 검정 대상으로 사용
stats.wilcoxon(df['weights']-120, alternative='less')

WilcoxonResult(statistic=np.float64(47.0), pvalue=np.float64(0.9814453125))

- 단일표본 비모수 검정에는 데이터 - 기준값으로 차이를 만든 뒤 wilcoxon()에 넣는 패턴을 기억해주자
- wilcoxon 검정은 평균이 아닌 중앙값에 대한 가설을 검증한다.

## 대응 표본 검정 (Paired t-test0)

### 대응 표본 검정
- 모집단이 1개 (같은 집단을 두번 측정)
- 같은 그룹의 두 시점(조건) 비교
- ex) 체중감량 프로그램 (전/후), 교육 프로그램 (전/후)

### 독립 표본 검정
- 모집단 2개
- 서로 다른 그룹(집단)을 비교
- ex) 두 반의 시험 성적 비교, 두 그룹의 임상실험 비교

In [10]:
import pandas as pd
# 같은 사람들의 '전(before)'과 '후(after)' 측정값 → 서로 짝지어진(paired) 데이터
df = pd.DataFrame({
    'before':[85, 90, 92, 88, 86, 89, 83, 87],
    'after':[85.5,89.9,92.6,89.5,85.8,88.8,84.6,87.8]
})

In [11]:
df

   before  after
0      85   85.5
1      90   89.9
2      92   92.6
3      88   89.5
4      86   85.8
5      89   88.8
6      83   84.6
7      87   87.8

In [13]:
from scipy import stats

# alternative='less'
# before-after의 평균이 0보다 작다. --> 검정
#   before < after
stats.ttest_rel(df['before'], df['after'], alternative='less')

# alternative='greater'
# after-before의 평균이 0보다 크다. --> 검정
#   before < after
stats.ttest_rel(df['after'], df['before'], alternative='greater')

## 위 둘은 같은 내용

TtestResult(statistic=np.float64(2.2127749675452324), pvalue=np.float64(0.03127028733756241), df=np.int64(7))

- 대응 표본 검정 문제는 "효과가 있는"를 묻는 경우가 많다.
- 양측 검정보다 단측 검정을 사용하는 빈도가 더 높다.
    - 사전보다 사후가 개선되었는지를 확인하는 방향성있는 질문이 대부분이기 때문.

### 비모수 검정 - 정규성이 깨졌을 떄

In [14]:
import pandas as pd
# 같은 사람들의 '전(before)'과 '후(after)' 측정값 → 서로 짝지어진(paired) 데이터
df = pd.DataFrame({
    'before':[85, 90, 92, 88, 86, 89, 83, 87],
    'after':[85.5,89.9,92.6,89.5,85.8,88.8,84.6,87.8]
})

In [15]:
from scipy import stats

# 두 그룹의 차이를 새 컬럼으로 만든다. -> 그 차이 값이 정규분포를 따르는지 검정
df['diff'] = df['after'] - df['before']
stats.shapiro(df['diff'])

ShapiroResult(statistic=np.float64(0.885486928626845), pvalue=np.float64(0.21232743678800203))

- t-검정 할 때는 순서가 결과 해석에 영향을 준다.
- shapiro()에 넣는 데이터 순서는 diff를 구했기 때문에 결과 해석에 영향을 주지 않는다.

In [16]:
stats.wilcoxon(df['after'], df['before'], alternative='greater')

WilcoxonResult(statistic=np.float64(30.0), pvalue=np.float64(0.05078125))

In [17]:
stats.wilcoxon(df['diff'], alternative='greater') # 위와 같다

WilcoxonResult(statistic=np.float64(30.0), pvalue=np.float64(0.05078125))