In [ ]:
import pandas as pd

festival = pd.read_csv('data/전국문화축제표준데이터.csv', encoding='cp949')

In [6]:
festival.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,NaN,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,NaN,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,NaN,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,NaN,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,NaN,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사

In [11]:
car_ = pd.read_csv('data/자동차등록현황보고_자동차등록대수현황 시도별 2026.csv', encoding='utf-8')
car_.head()

,월(Monthly),시도명,시군구,관용(승용),자가용(승용),영업용(승용),계(승용),관용(승합),자가용(승합),영업용(승합),...,영업용(화물),계(화물),관용(특수),자가용(특수),영업용(특수),계(특수),관용(총계),자가용(총계),영업용(총계),계(총계)
0,26-Jun,서울,강남구,156,"218,199","11,422","229,777",58,"3,612",557,...,"2,052","15,686",16,396,147,559,422,"235,649","14,178","250,249"
1,26-Jun,서울,강동구,109,"145,492","4,952","150,553",41,"2,930",601,...,"2,574","14,525",8,273,201,482,307,"160,497","8,328","169,132"
2,26-Jun,서울,강북구,116,"59,214","2,116","61,446",65,"1,834",710,...,"1,224","7,763",17,138,112,267,327,"67,596","4,162","72,085"
3,26-Jun,서울,강서구,136,"166,615","11,053","177,804",44,"3,665","1,385",...,"4,364","19,882",18,486,258,762,355,"186,127","17,060","203,542"
4,26-Jun,서울,관악구,88,"98,069","3,106","101,263",44,"2,519",360,...,"2,204","10,787",12,204,168,384,286,"109,233","5,838","115,357"

In [12]:
public_traffic = pd.read_csv('data/국내 지역별 문화향유를 위한 대중교통 시설 데이터.csv')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_2628\124824426.py:1: DtypeWarning: Columns (0: branch_nm, 1: rd_nm, 2: bld_num) have mixed types. Specify dtype option on import or set low_memory=False.
  public_traffic = pd.read_csv('data/국내 지역별 문화향유를 위한 대중교통 시설 데이터.csv')

In [13]:
public_traffic.head()

,id,lclas,mlsfc,id_poi,poi_nm,branch_nm,sub_nm,mcate_cd,mcate_nm,pnu,...,rd_cd,rd_nm,bld_num,x,y,grid_cd,lst_updt_dt,data_orgn,FILE_NAME,base_ymd
0,KCLPPPO25N000000001,장소,교통,10000524,잠두봉선착장,NaN,NaN,150206,기타선착장/나루터,1.144012e+18,...,NaN,NaN,NaN,126.908508,37.545200,다사477497,20251027,맵퍼스,KC_496_LLR_PPLTEQP_2025,20250822
1,KCLPPPO25N000000002,장소,교통,10007331,대전조차장역,NaN,NaN,150303,기타철도역명,3.023010e+18,...,3.023030e+11,아리랑로,166,127.421847,36.371021,다바929192,20251027,맵퍼스,KC_496_LLR_PPLTEQP_2025,20250822
2,KCLPPPO25N000000003,장소,교통,10013282,고양종합터미널,NaN,NaN,150501,고속버스터미널,4.128511e+18,...,4.128532e+11,중앙로,1036,126.789649,37.642918,다사373606,20251027,맵퍼스,KC_496_LLR_PPLTEQP_2025,20250822
3,KCLPPPO25N000000004,장소,교통,10066131,한국클린씨터미날,NaN,NaN,150503,화물/기타터미널,4.833025e+18,...,4.833033e+11,제방로,345,129.018383,35.319221,마마380036,20251027,맵퍼스,KC_496_LLR_PPLTEQP_2025,20250822
4,KCLPPPO25N000000005,장소,교통,10103445,부산철도차량정비단고속기지,NaN,NaN,150404,차량기지,2.623011e+18,...,2.623021e+11,신천대로,215,129.045566,35.160014,마라407860,20251027,맵퍼스,KC_496_LLR_PPLTEQP_2025,20250822